---
- name: Validate_ requirements
  ansible.builtin.include_tasks: validation.yml

- name: Deploy Hyperconverged Operator
  ansible.builtin.include_tasks: deploy-hco.yml
  when:
    - hs_deploy | bool
  tags:
    - install

- name: Deploy test Virtual Machine
  ansible.builtin.include_tasks: test-deploy-vm.yml
  when:
    - hs_test_vm | bool
  tags:
    - install
