---
# Always submit these files to DCI:
# - Configuration files - certsuite_config.yml
# - Execution logs - certsuite-stdout.log and certsuite.log, if they exist
- name: Copy config and log files related to certsuite execution
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ kbpc_log_path }}"
    mode: "0750"
  with_fileglob:
    - "{{ kbpc_certsuite_dir }}/config_files/*_config.yml"
    - "{{ kbpc_certsuite_dir }}/result_files/*.log"
  when:
    - kbpc_log_path is defined
    - kbpc_log_path|length

# Clean images just after finishing the execution
- name: Remove local certsuite image
  containers.podman.podman_image:
    name: "{{ kbpc_certsuite_image }}"
    state: absent
  ignore_errors: true

# Deleting resources created by the certsuite to support the execution
- name: Clean certsuite resources
  when: kbpc_postrun_delete_resources|bool
  block:
    - name: Delete cnf-suite Namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: cnf-suite
        state: absent
        wait: true

# This is just done when testing a certsuite stable version
- name: Delete temporary directory for git repos
  ansible.builtin.file:
    path: "{{ _kbpc_git_dir.path }}"
    state: absent
  when:
    - _kbpc_git_dir is defined
    - _kbpc_git_dir.path is defined

...
