---
- name: Copy files and subdirectories from source to target
  ansible.builtin.copy:
    src: "{{ car_source_dir | regex_replace('/$', '') }}/"
    dest: "{{ car_target_dir }}"
    mode: '0644'

- name: Find Jinja2 template files
  ansible.builtin.find:
    paths: "{{ car_source_dir }}"
    patterns: "*.j2"
    file_type: file
    recurse: true
  register: _car_j2_templates

- name: Render Jinja2 templates to target directory
  vars:
    # Relative paths starting with "./path/" are handled as "path/"
    src_dir: "{{ car_source_dir | regex_replace('^./', '') }}"
    target_path: "{{ item.path | replace(src_dir, car_target_dir) | regex_replace('\\.j2$', '') }}"
  ansible.builtin.template:
    src: "{{ item.path }}"
    dest: "{{ target_path }}"
    mode: '0644'
  loop: "{{ _car_j2_templates.files }}"

- name: Remove original .j2 template files from target directory
  vars:
    # Relative paths starting with "./path/" are handled as "path/"
    src_dir: "{{ car_source_dir | regex_replace('^./', '') }}"
    target_template: "{{ item.path | replace(src_dir, car_target_dir) }}"
  ansible.builtin.file:
    path: "{{ target_template }}"
    state: absent
  loop: "{{ _car_j2_templates.files }}"
...
