---
channel: ""
install_approval: "Manual"
olm_operator_skippable: false
operator_group_name: "{{ operator }}"
source_ns: openshift-marketplace
source: redhat-operators
starting_csv: ""
olm_operator_validate_install: true
...
