---
- name: Install operators
  ansible.builtin.include_tasks: install_operator.yml
  vars:
    rhoai_op_name: "{{ item }}"
    rhoai_op_package: "{{ __rhoai_operator_map[item].package }}"
    rhoai_op_channel: "{{ __rhoai_operator_map[item].channel }}"
    rhoai_op_namespace: "{{ __rhoai_operator_map[item].namespace }}"
  loop:  # install has to be in order
    - servicemesh
    - serverless
    - rhods

- name: Created DataScienceCluster
  ansible.builtin.include_tasks: create-dsc.yml
...
