---
- name: "Merge default and provided operator map"
  ansible.builtin.set_fact:
    __rhoai_operator_map: "{{ rhoai_default_operator_map | combine(rhoai_operator_map, recursive=true) }}"

- name: Validate_ operator map is complete
  ansible.builtin.assert:
    fail_msg: >
      Configuration for {{ item.key }} must contain package,
      channel, and namespace
    that:
      - "'package' in item.value"
      - "'channel' in item.value"
      - "'namespace' in item.value"
  loop: "{{ __rhoai_operator_map | dict2items }}"

- name: "Execute action {{ rhoai_action }}"
  ansible.builtin.include_tasks: "{{ rhoai_action }}.yml"
...
