---
- name: "Get Subscription info for {{ rhoai_op_name }}"
  kubernetes.core.k8s_info:
    kind: Subscription
    api_version: operators.coreos.com/v1alpha1
    name: "{{ rhoai_op_package }}"
    namespace: "{{ rhoai_op_namespace }}"
  register: _rhoai_sub

- name: "Removing Subscription for {{ rhoai_op_name }}"
  kubernetes.core.k8s:
    state: absent
    kind: Subscription
    api_version: operators.coreos.com/v1alpha1
    name: "{{ rhoai_op_package }}"
    namespace: "{{ rhoai_op_namespace }}"
    wait: true

- name: "Removing ClusterServiceVersion for {{ rhoai_op_name }}"
  when: _rhoai_sub.resources | length == 1
  kubernetes.core.k8s:
    state: absent
    kind: ClusterServiceVersion
    api_version: operators.coreos.com/v1alpha1
    name: "{{ _rhoai_sub.resources[0].status.currentCSV }}"
    namespace: "{{ rhoai_op_namespace }}"
    wait: true

- name: "Removing leftover webhook configs for {{ rhoai_op_name }}"
  kubernetes.core.k8s:
    state: absent
    kind: "{{ __kind }}"
    name: "{{ rhoai_op_namespace }}.{{ rhoai_op_name }}-resources.maistra.io"
  loop:
    - ValidatingWebhookConfiguration
    - MutatingWebhookConfiguration
  loop_control:
    loop_var: __kind

- name: "Removing OperatorGroup for {{ rhoai_op_name }}"
  kubernetes.core.k8s:
    state: absent
    kind: OperatorGroup
    api_version: operators.coreos.com/v1
    name: "{{ rhoai_op_package }}"
    namespace: "{{ rhoai_op_namespace }}"

- name: "Removing namespace for {{ rhoai_op_name }}"
  kubernetes.core.k8s:
    state: absent
    kind: Namespace
    api_version: v1
    name: "{{ rhoai_op_namespace }}"
    wait: true
...
