---
- name: Check ansible version
  ansible.builtin.fail:
    msg: Use Ansible version 2.9 or greater to run this playbook
  when: ansible_version.full is version('2.9.0', '<')
  delegate_to: localhost
  tags:
    - always
    - validation
    - fully_disconnected

- name: Ensure Python libraries are installed
  community.general.python_requirements_info:
    dependencies:
      - netaddr
  register: _py_facts
  delegate_to: localhost
  tags:
    - always
    - validation

- name: Fail if version is undefined, empty, or not valid.
  ansible.builtin.assert:
    fail_msg: "The version is undefined or not valid. Use a value such as 'latest-4.8' or an explicit version i.e.: '4.8.2'."
    that:
      - ver is defined
      - ver is version("4.8", ">=")
  vars:
    ver: "{{ version.split('latest-')[1] | default(version) }}"
  tags:
    - always
    - validation

- name: Fail if build is undefined, empty or not valid.
  ansible.builtin.assert:
    fail_msg: "The build is undefined, empty or not valid. Use a value such as 'nightly', 'dev' or 'ga'."
    that:
      - build is defined
      - build in ("dev", "ga", "nightly")
  tags:
    - always
    - validation

- name: Fail if a required install-config variable is undefined or empty.
  ansible.builtin.assert:
    fail_msg: "A variable regarding install-config.yml is undefined or empty."
    that:
      - domain is defined
      - domain|length != 0
      - cluster is defined
      - cluster|length != 0
      - extcidrnet is defined
      - extcidrnet|length != 0
      - pullsecret is defined
      - pullsecret|length != 0
  tags:
    - always
    - validation

- name: Set release_url
  ansible.builtin.set_fact:
    release_url: "{{ (webserver_url | length) | ternary(webserver_url, '/'.join(hostvars.localhost.url.split('/')[:-1])) }}"
  tags:
    - always
    - validation


- name: Fail if dualstack_baremetal and ipv4_baremetal are both true
  ansible.builtin.fail:
    msg: >
      Only one of ipv4_baremetal and dualstack_baremetal variables can be true
  when: ipv4_baremetal and dualstack_baremetal
  tags:
    - always
    - validation

- name: Check for valid extcidrnet (IPv4)
  ansible.builtin.fail:
    msg: extcidrnet should be a valid IPv4 CIDR
  when: not ipv6_enabled|bool and not extcidrnet|ipv4
  tags:
    - always
    - validation

- name: Check for valid extcidrnet (IPv6)
  ansible.builtin.fail:
    msg: extcidrnet6 should be a valid IPv6 address
  when:
    - ipv6_enabled | bool
    - not (ipv4_baremetal or dualstack_baremetal)
    - not extcidrnet6 | ipv6
  tags:
    - always
    - validation

- name: Check for valid extcidrnet and extcidrnet6 (Dual-Stack)
  ansible.builtin.fail:
    msg: extcidrnet should be a valid IPv4 address and extcidrnet6 should be a valid IPv6 address
  when:
    - ipv6_enabled | bool
    - dualstack_baremetal | bool
    - not (extcidrnet | ipv4 and extcidrnet6 | ipv6)
  tags:
    - always
    - validation

- name: Gather the rpm package facts
  ansible.builtin.package_facts:
    manager: auto
  tags:
    - always
    - validation
  when:
    - ansible_facts.packages | default([]) | length < 1

- name: Set Fact for firewall variable
  ansible.builtin.set_fact:
    firewall: "iptables"
  when: "'iptables-services' in ansible_facts.packages"
  tags:
    - always
    - validation

- name: "Ensure cache_dir is created"
  ansible.builtin.file:
    path: "{{ snp_cache_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"
  become: true
...
