---
mor_base_version: "{{ mor_version.split('.')[:2] | join('.') }}"
mor_cache_dir: "/var/lib/dci-openshift-agent/releases"
mor_install_type: "ipi"
mor_installer: >-
  {{ mor_version is version('4.16', '>=') |
  ternary('openshift-install', 'openshift-baremetal-install') }}
mor_is_type: >-
  {{ mor_version is version('4.14', '>=') |
  ternary('idms', 'icsp') }}
mor_owner: "{{ ansible_user_uid }}"
mor_group: "{{ ansible_user_gid }}"
mor_force: false
mor_mirror_disk_images: true
mor_mirror_container_images: true
mor_write_custom_config: true
mor_registry_path: "ocp-{{ mor_base_version }}/{{ mor_version }}"
mor_allow_insecure_registry: true
# Required images according install type
mor_ipi:
 - openstack
 - qemu
 - metal_iso
mor_vsphere:
 - openstack
 - qemu
mor_sno:
 - metal_pxe_rootfs
 - metal_iso
mor_acm:
 - metal_pxe_rootfs
 - metal_iso
mor_assisted_installer:
 - metal_pxe_rootfs
 - metal_iso
mor_abi:
 - metal_pxe_rootfs
 - metal_iso
...
