---
- name: Print JSON draft for the project to be created
  vars:
    template_filename: "templates/create_project_{{ product_type }}.json.j2"
  ansible.builtin.debug:
    msg: "{{ lookup('template', template_filename) }}"

- name: Create certification project
  vars:
    template_filename: "templates/create_project_{{ product_type }}.json.j2"
  ansible.builtin.uri:
    url: "{{ catalog_url }}/projects/certification"
    method: POST
    headers:
      X-API-KEY: "{{ lookup('file', pyxis_apikey_path) }}"
    body_format: json
    body: "{{ lookup('template', template_filename) }}"
    status_code: 201
    timeout: 120
  register: cert_project_output

- name: Set project ID to reuse it later
  ansible.builtin.set_fact:
    ccp_cert_project_id: "{{ cert_project_output.json | json_query('_id') }}"
  when: not cert_project_output.failed

- name: Set and Save New Project IDs for Preflight Parallel Tests
  ansible.builtin.set_fact:
    ccp_new_cert_project_ids: "{{ ccp_new_cert_project_ids | default([]) + [{'pyxis_container_identifier': ccp_cert_project_id}] }}"
  when:
    - not cert_project_output.failed
    - do_container_parallel_test

- name: Print the URL of created certification project
  ansible.builtin.debug:
    msg: |
      Certification project was created and could be checked here:
      {{ connect_url }}/{{ ccp_cert_project_id }}/overview
  when: not cert_project_output.failed
...
