---
- name: Validate_ inputs
  ansible.builtin.assert:
    that:
      - mi_registry is defined
      - mi_images is defined
      - mi_images | length

- name: "Mirror images"
  ansible.builtin.include_tasks: mirror-images.yml
  loop: "{{ mi_images }}"
  loop_control:
    loop_var: image
