---
- name: "Delete tmp tool directory"
  ansible.builtin.file:
    state: absent
    path: "{{ cv_tool_dir.path }}"
  when:
    - cv_tool_dir is defined
    - cv_tool_dir.path is defined

- name: "Delete work_dir directory"
  ansible.builtin.file:
    state: absent
    path: "{{ tmp_dir.path }}"
  when:
    - tmp_dir
    - tmp_dir.path is defined

- name: "Delete the one time use key from Github"
  ansible.builtin.command: "{{ gh_tool_path }} api -X DELETE user/keys/{{ key_id }}"
  ignore_errors: true

- name: "GH logout"
  ansible.builtin.command: "{{ gh_tool_path }} auth logout --hostname github.com"
  failed_when: false
...
