---
- name: "Delete tmp tool directory"
  ansible.builtin.file:
    state: absent
    path: "{{ cv_tool_dir.path }}"
  when:
    - cv_tool_dir is defined
    - cv_tool_dir.path is defined

- name: "Delete work_dir directory"
  ansible.builtin.file:
    state: absent
    path: "{{ tmp_dir.path }}"
  when:
    - tmp_dir
    - tmp_dir.path is defined
...
