---
- name: "Validate parameters"
  ansible.builtin.assert:
    that: "{{ item }} is defined"
    fail_msg: "The parameter {{ item }} is required"
  with_items:
    - kubeconfig_path
    - ocp_version_full
    - dci_charts
    - organization_id

- name: "Get partner name"
  ansible.builtin.include_tasks: get-partner-name.yml

# Get tools like yq and helm
- name: "Get tools"
  ansible.builtin.include_tasks: get-tools.yml

## Temporary disabled, failing with images
## with format like rhscl/mongodb-36-rhel7:1-65
# - name: "Mirror chart images"
#   include_tasks: mirror-chart-images.yml
#   when: dci_disconnected | default(false) | bool

- name: "Set Logs path"
  ansible.builtin.set_fact:
    logs_dir: "{{ job_logs.path | default('/tmp') }}"

- name: "Set target repository"
  ansible.builtin.set_fact:
    target_repository: "{{ sandbox_repository | default('openshift-helm-charts/charts') }}"

- name: "Render submission report header"
  vars:
    partner: "{{ partner_name | replace(' ', '_') }}"
  ansible.builtin.template:
    mode: "0755"
    src: report.j2
    dest: "{{ logs_dir }}/helm-submission-report.txt"

- name: "Run the tests"
  ansible.builtin.include_tasks: tests.yml
  loop: "{{ dci_charts }}"
  loop_control:
    loop_var: chart
    index_var: index
...
