---
- name: Deploy CR {{ dc_kind }}
  kubernetes.core.k8s:
    definition:
      apiVersion: "{{ dc_api_version }}"
      kind: "{{ dc_kind }}"
      metadata:
        name: "{{ dc_name }}"
        namespace: "{{ dc_namespace | default(omit) }}"
      spec: "{{ dc_spec }}"
  register: _deploy_cr_create_result
  retries: 5
  delay: 60
  until: _deploy_cr_create_result is not failed

- name: Validate_ that the CR is ready
  kubernetes.core.k8s_info:
    api_version: "{{ dc_api_version }}"
    name: "{{ dc_name }}"
    namespace: "{{ dc_namespace | default(omit) }}"
    kind: "{{ dc_kind }}"
    wait: true
    wait_condition: "{{ dc_wait_condition }}"
    wait_timeout: "{{ dc_wait_timeout }}"
  register: _deploy_cr_result
  retries: "{{ dc_wait_retries }}"
  delay: "{{ dc_wait_delay }}"
  until: _deploy_cr_result is not failed
  when: dc_wait_for_cr | bool

- name: Pause to wait for MCP to be updated if any
  ansible.builtin.pause:
    seconds: 60

- name: Wait for MCPs changes applied if any
  ansible.builtin.include_role:
    name: redhatci.ocp.check_resource
  vars:
    resource_to_check: "MachineConfigPool"          # noqa: redhat-ci[no-role-prefix]
    check_wait_retries: "{{ dc_wait_mc_retries }}"  # noqa: redhat-ci[no-role-prefix]
    check_wait_delay: "{{ dc_wait_mc_delay }}"      # noqa: redhat-ci[no-role-prefix]
...
