---
- name: Setup HTTP Store
  block:
    - name: Install podman
      ansible.builtin.package:
        name: podman
        state: present
      become: true

    - name: Open http port, zone internal and public, for firewalld
      ansible.builtin.firewalld:
        port: "{{ http_port }}/tcp"
        permanent: true
        immediate: true
        state: enabled
        zone: "{{ item }}"
      loop:
        - internal
        - public
      become: true

    - name: Create directory to hold the registry files
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ file_owner }}"
        group: "{{ file_group }}"
        mode: "0775"
        recurse: true
      loop:
        - "{{ http_dir }}"
        - "{{ http_data_dir }}"
      become: true

    - name: Ensure variable http_store_ip_version has a valid value
      ansible.builtin.assert:
        that: "http_store_ip_version == 'ipv4' or http_store_ip_version == 'ipv6'"
        fail_msg: "http_store_ip_version variable is neither ipv4 nor ipv6"

    - name: Set IP version to publish in pod with respective http_store port
      ansible.builtin.set_fact:
        http_ip_ver_port: "{{ http_store_ip_version == 'ipv4' |
                    ternary(http_port, '[::]:'+ http_port) }}"

    - name: Create httpd pod
      containers.podman.podman_pod:
        name: "{{ http_store_pod_name }}"
        publish:
          - "{{ http_ip_ver_port }}:8080"
      register: pod_info
      become: "{{ not (http_store_ephemeral | bool) }}"

    - name: Debug
      ansible.builtin.debug:
        var: pod_info
        verbosity: 1

    - name: Create httpd container
      vars:
        container_status: "{{ http_store_ephemeral | ternary('started', 'stopped') }}"
      containers.podman.podman_container:
        name: "{{ http_store_container_name }}"
        image: "{{ container_image }}"
        pod: "{{ http_store_pod_name }}"
        state: "{{ container_status }}"
        volumes:
          - "{{ http_data_dir }}:/var/www/html:z"
      register: container_info
      become: "{{ not (http_store_ephemeral | bool) }}"

    - name: Configure HTTP Store systemd service
      when:
        - not http_store_ephemeral | bool
      become: true
      block:
        - name: Copy the systemd service file
          vars:
            http_store_pidfile: "{{ container_info.container.ConmonPidFile }}"
          ansible.builtin.copy:
            content: |
              [Unit]
              Description=Podman http_store.service
              [Service]
              Restart=on-failure
              ExecStart=/usr/bin/podman pod start {{ http_store_pod_name }}
              ExecStop=/usr/bin/podman pod stop -t 10 {{ http_store_pod_name }}
              KillMode=none
              Type=forking
              PIDFile={{ http_store_pidfile }}
              [Install]
              WantedBy=default.target
            dest: "/etc/systemd/system/http_store.service"
            mode: "0644"

        - name: Reload systemd service
          ansible.builtin.systemd:
            daemon_reexec: true
            scope: system

        - name: Enable http_store.service
          ansible.builtin.systemd:
            name: http_store
            enabled: true
            scope: system

        - name: Start http_store.service
          ansible.builtin.systemd:
            name: http_store
            state: started
            scope: system
