- name: Create podman auth dir
  ansible.builtin.file:
    path: "{{ generated_dir }}/containers/"
    state: directory
    mode: '0755'
    recurse: true

- name: Copy pull_secrets file.
  ansible.builtin.copy:
    content: "{{ pull_secret }}"
    dest: "{{ generated_dir }}/containers/auth.json"
    mode: "0644"
    remote_src: true

- name: Fail if required nmstatectl is not installed
  ansible.builtin.command: type nmstatectl
  register: _gai_nmstatectl_check
  failed_when: _gai_nmstatectl_check.rc != 0
  changed_when: _gai_nmstatectl_check.rc != 0

- name: Generate agent ISO
  ansible.builtin.command:
    cmd: "{{ agent_based_installer_path }} --log-level=debug agent create image"
    chdir: "{{ manifests_dir }}"
  environment:
    XDG_RUNTIME_DIR: "{{ generated_dir }}"
  changed_when: _gai_gen_iso.rc != 0
  register: _gai_gen_iso
  retries: 3
  delay: 15
  until:
    - _gai_gen_iso.rc == 0

- name: Put discovery iso in http store
  delegate_to: http_store
  become: true
  block:
    - name: Create discovery directory
      ansible.builtin.file:
        path: "{{ download_dest_path }}/{{ download_agent_dest_file | dirname }}"
        recurse: true
        state: directory

    - name: Copy agent iso to discovery directory
      ansible.builtin.copy:
        src: "{{ manifests_dir }}/agent.{{ arch }}.iso"
        dest: "{{ download_dest_path }}/{{ download_agent_dest_file }}"
        mode: '0644'
