---
- name: Fail if sg_local_registry is defined but sg_pullsecret_file is not
  ansible.builtin.fail:
    msg: "sg_pullsecret_file is required when sg_local_registry is defined."
  when: sg_local_registry is defined and sg_pullsecret_file is not defined

- name: Mirror ZTP/MCE images
  vars:
    mi_images: >-
      {{
        [
          (sg_ztp_repo + ':' + sg_ztp_tag ),
          (sg_mce_repo + ':' + sg_mce_tag )
        ]
      }}
    mi_authfile: "{{ sg_pullsecret_file }}"
    mi_registry: "{{ sg_local_registry }}"
  ansible.builtin.include_role:
    name: redhatci.ocp.mirror_images

- name: Set image fact for repo server in local registry
  ansible.builtin.set_fact:
    sg_ztp_repo: "{{ sg_local_registry }}/openshift4/ztp-site-generate-rhel8"
    sg_mce_repo: "{{ sg_local_registry }}/rhacm2/multicluster-operators-subscription-rhel9"
...
