---
- name: "Pre-run validations"
  ansible.builtin.include_tasks: pre-run.yml

- name: "Check cluster namespace"
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Namespace
    name: "{{ acm_cluster_name }}"
  register: acm_cluster_ns

- name: "Fail if a cluster namespace already exists"
  ansible.builtin.fail:
    msg: >
      A namespace for the specified cluster name {{ acm_cluster_name }} already
      exist. Set acm_force_deploy:true to delete it
  when:
    - acm_cluster_ns.resources | length == 1
    - not acm_force_deploy | bool

- name: "Delete current cluster"
  ansible.builtin.include_tasks: delete-cluster.yml
  when:
    - acm_force_deploy | bool

- name: "Install a new cluster"
  ansible.builtin.include_tasks: create-cluster.yml

- name: "Monitor installation progress"
  ansible.builtin.include_role:
    name: redhatci.ocp.acm.utils
    tasks_from: monitor-install
  vars:
    utils_cluster_name: "{{ acm_cluster_name }}"
    utils_cluster_namespace: "{{ acm_cluster_name }}"
    utils_monitor_timeout: 90
    utils_monitor_wait_time: 5

- name: "Get spoke cluster credentials"
  ansible.builtin.include_role:
    name: redhatci.ocp.acm.utils
    tasks_from: get-credentials
  vars:
    utils_cluster_name: "{{ acm_cluster_name }}"
    utils_cluster_namespace: "{{ acm_cluster_name }}"
...
