---
- name: Set resource kind
  ansible.builtin.set_fact:
    cr_kind: "{{ resource_to_check }}"
  when: resource_to_check is defined

- name: Check MachineConfigPool
  ansible.builtin.include_tasks:
    file: wait-mcp.yml
  when: cr_kind == "MachineConfigPool"

- name: Check SriovNetworkNodeState
  ansible.builtin.include_tasks:
    file: wait-sriov.yml
  when: cr_kind == "SriovNetworkNodeState"

...
