---
- name: Pause 60 seconds to wait for SriovNetworkNodeState to start the node update
  ansible.builtin.pause:
    seconds: 60

- name: Wait until SriovNetworkNodeState becomes ready
  vars:
    query_sync_status: 'resources[*].status.syncStatus'
    query_sync_status_results: "{{ _cr_sriovnetnode | json_query(query_sync_status) }}"
  kubernetes.core.k8s_info:
    api_version: sriovnetwork.openshift.io/v1
    kind: SriovNetworkNodeState
  register: _cr_sriovnetnode
  until:
    - _cr_sriovnetnode.resources is defined
    - query_sync_status_results | unique == ['Succeeded']
  retries: "{{ check_wait_retries }}"
  delay: "{{ check_wait_delay }}"

...
