---
- name: "Pause 60 seconds to wait for MC to be triggered by a resource change"
  ansible.builtin.pause:
    seconds: 60

- name: Wait for MCP to be updated
  kubernetes.core.k8s_info:
    api_version: machineconfiguration.openshift.io/v1
    kind: MachineConfigPool
  register: _cr_mcp_status
  vars:
    _cr_status_query: "resources[*].status.conditions[?type=='Updated'].status"
    _cr_update_status: "{{ _cr_mcp_status | json_query(_cr_status_query) | flatten | unique }}"
  until:
    - _cr_mcp_status.resources is defined
    - _cr_update_status == ['True']
  retries: "{{ check_wait_retries }}"
  delay: "{{ check_wait_delay }}"

...
