---
- name: Wait until sriovnetworknodestate becomes ready
  kubernetes.core.k8s_info:
    api_version: sriovnetwork.openshift.io/v1
    kind: SriovNetworkNodeState
  register: sriovnetnode
  until: sriovnetnode.resources is defined and sriovnetnode.resources | selectattr('status.syncStatus', 'defined') | list | rejectattr('status.syncStatus', 'equalto', 'Succeeded') | list | count == 0
  retries: "{{ check_wait_retries }}"
  delay: "{{ check_wait_delay }}"

...
