---
- name: Include IPMI nodes variables
  ansible.builtin.include_vars:
    file: "{{ ocp_on_libvirt_vbmc_ipmi_nodes }}"
    name: ironic_nodes

- name: Generating hosts inventory file
  ansible.builtin.template:
    src: hosts.j2
    dest: "{{ inventory_prefix }}hosts"
    mode: "0750"
  vars:
    input_prefix: "{{ lookup('env', 'PREFIX') }}"
    inventory_prefix: "{{ (input_prefix | replace('-p ', '')) + '-' if input_prefix != '' else '' }}"
  delegate_to: localhost

- name: Update running inventory of masters
  ansible.builtin.add_host:
    name: "{{ item.key }}"
    groups:
      - masters
    ipmi_user: "{{ item.value.ipmi_user }}"
    ipmi_password: "{{ item.value.ipmi_pass }}"
    ipmi_address: "{{ item.value.ipmi_address }}"
    ipmi_port: "{{ item.value.ipmi_port }}"
    socket_console: "{{ enable_conserver }}"
  when: '"master" in item.key'
  loop: "{{ ironic_nodes | dict2items }}"

- name: Update running inventory of workers
  ansible.builtin.add_host:
    name: "{{ item.key }}"
    groups:
      - workers
    ipmi_user: "{{ item.value.ipmi_user }}"
    ipmi_password: "{{ item.value.ipmi_pass }}"
    ipmi_address: "{{ item.value.ipmi_address }}"
    ipmi_port: "{{ item.value.ipmi_port }}"
    socket_console: "{{ enable_conserver }}"
  when: '"workers" in item.key'
  loop: "{{ ironic_nodes | dict2items }}"

- name: Startup provisionhost
  community.libvirt.virt:
    name: "{{ item.key }}"
    state: running
  loop: "{{ lookup('dict', ironic_nodes) }}"
  when: "'provision' in item.key"
