---
- name: "Fail if no network configuration is provided when using Grout as CNFApp"
  ansible.builtin.fail:
    msg: "If using Grout as CNFApp, network configuration file must be provided"
  when:
    - ecd_cnfapp_name == "grout"
    - ecd_network_config_file|length == 0

- name: "Check nodes and set deployment type"
  ansible.builtin.include_tasks: check_nodes.yml

- name: "Find versions from the catalog"
  ansible.builtin.shell:
    cmd: >
      set -e -o pipefail;
      {{ ecd_opm_path }} render
      {{ ecd_catalog_image }} |
      jq -rn 'inputs | select(.schema == "olm.bundle").relatedImages[].image'
  args:
    executable: /bin/bash
  register: _ecd_catalog_data_cmd
  retries: 1
  delay: 5
  until:
    - _ecd_catalog_data_cmd.rc == 0

- name: "Set trex-app version from the catalog"
  ansible.builtin.set_fact:
    ecd_trex_app_version: "{{ item }}"
  when: '"trex-container-app@" in item'
  loop: "{{ _ecd_catalog_data_cmd.stdout_lines }}"

- name: "Set trex-server version from the catalog"
  ansible.builtin.set_fact:
    ecd_trex_server_version: "{{ item }}"
  when: '"trex-container-server@" in item'
  loop: "{{ _ecd_catalog_data_cmd.stdout_lines }}"

- name: "Installation of example-cnf operators"
  ansible.builtin.include_tasks: deploy/sub.yml

- name: "Deployment of example-cnf applications"
  ansible.builtin.include_tasks: deploy/app.yml
