---
- name: "CNFApp must be TestPMD"
  ansible.builtin.assert:
    that: ecd_cnfapp_name == 'testpmd'

- name: Gather facts
  ansible.builtin.include_tasks: draining/gather-facts.yml

- name: Drain the worker node where testpmd is running
  ansible.builtin.include_tasks: draining/node-draining.yml

- name: Validate_ allocation of new testpmd pod
  ansible.builtin.include_tasks: draining/testpmd-validation.yml

- name: Validate_ TRex job
  ansible.builtin.include_tasks: draining/trex-validation.yml
