---

- name: Run validation tasks if the automation deployment was previously launched
  when: ecd_run_deployment == 1
  block:
    - name: "Migrate tasks"
      ansible.builtin.include_tasks: validate/migrate.yml

    - name: "Validate tasks"
      ansible.builtin.include_tasks: validate/validate.yml
      when: ecd_try_running_migration_tests|bool
