---
# tasks file for monitor_cluster

- name: Deprecation warning
  ansible.builtin.debug:
    msg:
      - "[DEPRECATION WARNING]: This role will be removed from the collection in the future."
      - "Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg."
  when:
    - lookup('ansible.builtin.config', 'DEPRECATION_WARNINGS')

- name : Get cluster status during installation
  uri:
    url: "{{ URL_ASSISTED_INSTALLER_CLUSTER }}"
    method: GET
    status_code: [200, 201]
    return_content: True
  register: cluster_output
  delegate_to: bastion
  until: cluster_output is successful
  retries: 4
  delay: 30

- debug: # noqa unnamed-task
    msg: "{{ cluster_output.json.hosts }}"
    verbosity: 1

- name: Identify the host
  set_fact:
    monitor_host_current_host: "{{ item }}"
  loop: "{{ cluster_output.json.hosts }}"
  when: item.requested_hostname == inventory_hostname
  no_log: true


- debug: # noqa unnamed-task
    msg: "{{ monitor_host_current_host }}"
    verbosity: 1

- name: Start host monitoring
  include_tasks: hosts_monitoring.yml
  args:
    apply:
      delegate_to: bastion
  vars:
    host_id: "{{ monitor_host_current_host.id }}"
    host_name: "{{ monitor_host_current_host.requested_hostname }}"
  no_log: true
