---
- name: Create /var/consoles/{{ cluster }}
  become: true
  ansible.builtin.file:
    path: /var/consoles/{{ cluster }}
    mode: "0755"
    state: directory

- name: Check for Serial over IPMI
  ansible.builtin.command:
    cmd: >
      ipmitool -H {{ hostvars[item].ipmi_address }}
               -U {{ hostvars[item].ipmi_user }}
               -P {{ hostvars[item].ipmi_password }}
               -p {{ hostvars[item].ipmi_port | default(623) }}
               -I lanplus
               sol info
  register: _conserver_sol
  ignore_errors: true
  changed_when: true
  loop: "{{ cluster_nodes }}"

- name: Build list of Serial over IPMI hosts
  ansible.builtin.set_fact:
    conserver_sol_hosts: "{{ conserver_sol_hosts + [item.item] }}"
  when: item.rc == 0
  loop: "{{ _conserver_sol.results | default([]) }}"

- name: Include IPMI console config
  ansible.builtin.include_tasks: config-ipmi.yml
  when: conserver_sol_hosts | length > 0

- name: Build list of Serial over SOCKET hosts (libvirt)
  ansible.builtin.set_fact:
    conserver_socket_hosts: "{{ conserver_socket_hosts + [item] }}"
  when: hostvars[item].socket_console | default(false) | bool
  loop: "{{ cluster_nodes }}"

- name: Include libvirt console config
  ansible.builtin.include_tasks: config-libvirt.yml
  when: conserver_socket_hosts | length > 0
