---
- name: Get Kubeconfig secret
  kubernetes.core.k8s_info:
    api: v1
    kind: Secret
    name: "{{ utils_cluster_name }}-admin-kubeconfig"
    namespace: "{{ utils_cluster_namespace }}"
  register: kubeconfig_secret
  retries: 15
  delay: 10
  until:
    - kubeconfig_secret.resources is defined
    - kubeconfig_secret.resources | length
  no_log: true

- name: Get kubeadmin credentials
  kubernetes.core.k8s_info:
    api: v1
    kind: Secret
    name: "{{ utils_cluster_name }}-admin-password"
    namespace: "{{ utils_cluster_namespace }}"
  register: kubeconfig_password
  retries: 15
  delay: 10
  until:
    - kubeconfig_password.resources is defined
    - kubeconfig_password.resources | length
  no_log: true

- name: Set credentials facts
  vars:
    _default_user: "{{ 'kubeadmin' | b64encode }}"
  ansible.builtin.set_fact:
    acm_kubeconfig_text: '{{ kubeconfig_secret.resources[0].data["kubeconfig"] | b64decode }}'
    acm_kubeconfig_user: '{{ kubeconfig_password.resources[0].data["username"] | default(_default_user) | b64decode }}'
    acm_kubeconfig_pass: '{{ kubeconfig_password.resources[0].data["password"] | b64decode }}'
  no_log: true
...
