---
- name: Add Storage node labels
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Node
      metadata:
        name: "{{ hostvars[node].name }}"
        labels:
          "{{ hostvars[node].lso_label }}"
  loop: "{{ groups['ocs_nodes'] }}"
  loop_control:
    loop_var: node
    label: "{{ hostvars[node].name }}"
  when:
    - groups['ocs_nodes'] is defined
    - hostvars[node].lso_label is defined

- name: Deploying DaemonSet to gather disk-id on nodes
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'ocs-disk-gatherer.yml.j2') }}"
    state: present
    wait: true
    wait_timeout: 300

- name: Gathering result from DaemonSet
  ansible.builtin.shell:
    cmd: >
      sleep 90;
      {{ odf_setup_oc_tool_path }} logs
      --selector name=ocs-disk-gatherer
      --tail=-1
      --since=10m
      --namespace ocs-disk-gatherer
  register: disk_id

- name: Configure Local Storage Volumes
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'local-storage-block.yml.j2') }}"
  register: local_storage_volcrd

- name: Remove DaemonSet ocs-disk-gatherer
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'ocs-disk-gatherer.yml.j2') }}"
    state: absent
    wait: true

- name: Check LSO Storage Class exists
  kubernetes.core.k8s_info:
    kind: StorageClass
    name: "{{ local_storage_class }}"
  register: lso_storage_class
  retries: 30
  delay: 10
  until: lso_storage_class.resources != []
...
