---
- name: Validate_ requirements
  ansible.builtin.include_tasks: validation.yml

- name: Set Facts
  ansible.builtin.include_tasks: set-facts.yml

- name: Setup Local Storage operator
  ansible.builtin.include_tasks: local-storage-operator.yml
  when:
    - ocs_install_type == 'internal'

- name: Setup Openshift Storage Operator
  ansible.builtin.include_tasks: openshift-storage-operator.yml

- name: Perform OCS Tests
  ansible.builtin.include_tasks: tests.yml
...
