---
- name: "Check if the OCS CRD is present"
  block:
    - kubernetes.core.k8s_info:
        kind: CustomResourceDefinition
        name: storageclusters.ocs.openshift.io
      register: req_crd
      retries: 12
      delay: 10
      until: req_crd.resources | length > 0
      no_log: true
  rescue:
    - name: "Fail if OCS CRD is not present"
      ansible.builtin.fail:
        msg: "OCS CRDs are not present, please install the Openshift Cluster Storage Operator"
      when: req_crd.resources | list | count == 0
        
- name: "Check if the main LSO CRD is present"
  kubernetes.core.k8s_info:
    kind: CustomResourceDefinition
    name: localvolumes.local.storage.openshift.io
  register: req_crd
  no_log: true

- name: "Fail if Local Storage CRD is not present"
  ansible.builtin.fail:
    msg: "LSO CRD are not present, please install the Local Storage Operator"
  when:
    - req_crd.resources | list | count == 0
    - ocs_install_type == 'internal'

- name: "Validate OCS external variables"
  ansible.builtin.assert:
    that:
      - external_ceph_data is defined
  when:
    - ocs_install_type == 'external'

- name: "Check minimal number of nodes for replicas for LSO"
  when:
    - ocs_install_type == 'internal'
  block:
    - name: Get node information from Kubernetes
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Node
        label_selectors:
          - "cluster.ocs.openshift.io/openshift-storage"
      register: nodes_info

    - name: Fail if there are not at least 3 nodes for OCS
      ansible.builtin.fail:
        msg: >
          There are less than 3 nodes with the label
          cluster.ocs.openshift.io/openshift-storage
      when: nodes_info.resources | length < 3

- name: Assert that local_storage_devices is defined and is a list with at least one item
  ansible.builtin.assert:
    that:
      - local_storage_devices is defined
      - local_storage_devices | length > 0
    fail_msg: "local_storage_devices must be a list with at least one item"
...
