---
- name: Create ArgoCD App
  when:
    - ac_action == "create"
  ansible.builtin.include_tasks:
    file: config-app-create.yml

- name: Delete ArgoCD App
  when:
    - ac_action in ['delete', 'delete-cascade']
  ansible.builtin.include_tasks:
    file: config-app-delete.yml

- name: Change Sync in ArgoCD App
  when:
    - ac_action in  ['sync-on', 'sync-off']
  ansible.builtin.include_tasks:
    file: config-app-sync.yml
