---
# OCPBUGS-32139 workaround suggests to retry the creation of the SRIOV policy if failing.
# Trying this during 1 minute in case any of them fails.
- name: Create SriovNetworkNodePolicy
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'templates/sriov-network-node-policy.yml.j2') }}"
  loop: "{{ sriov_network_configs }}"
  loop_control:
    loop_var: sriov
    label: "{{ sriov.resource }}"
  retries: 6
  delay: 10
  register: _sc_node_policy_retry
  until: _sc_node_policy_retry.error is not defined
  when: sriov.node_policy is defined

- name: Check for SRIOV Node Policy
  ansible.builtin.include_tasks: check_sriov_node_policy.yml
  loop: "{{ sriov_network_configs }}"
  loop_control:
    loop_var: sriov_conf
    label: "{{ sriov_conf.resource }}"
  when:
    - sriov_conf.node_policy is defined
    - sriov_config_wait_node_policy | bool
