---
- name: Validate_ SR-IOV requirements
  ansible.builtin.include_tasks: validation.yml

- name: Create SriovNetworkNodePolicies
  ansible.builtin.include_tasks: create_node_policies.yml
  when: sriov_network_configs | json_query('[*].node_policy') | select('defined') | list | length

- name: Create SriovNetworks
  ansible.builtin.include_tasks: create_networks.yml
  when: sriov_network_configs | json_query('[*].network') | select('defined') | list | length
