---
- name: "Verify the presence of file in the log folder"
  ansible.builtin.stat:
    path: "{{ item }}"
  register: junit_file

- name: "Test_ if the file is present in the log folder"
  ansible.builtin.fail:
    msg: "Could not verify test results: {{ item | basename }} is not present"
  failed_when:
    - not junit_file.stat.exists
    # Do not fail when the option to skip missing files is on
    - not skip_absent_testfiles | bool

- name: "Retrieve the actual test results from {{ item | basename }}"
  ansible.builtin.set_fact:
    actual_results: "{{ item | redhatci.ocp.junit2dict }}"

- name: "Validate_ all test results are as expected for {{ item | basename }}"
  vars:
    expectation_failed: "{{ t.expected_results | redhatci.ocp.regex_diff(actual_results) }}"
  ansible.builtin.fail:
    msg: "The following expectations failed: {{ expectation_failed }}"
  when: expectation_failed | length > 0
...
