---
# tasks file for monitor_cluster

- name: Deprecation warning
  ansible.builtin.debug:
    msg:
      - "[DEPRECATION WARNING]: This role will be removed from the collection in the future."
      - "Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg."
  when:
    - lookup('ansible.builtin.config', 'DEPRECATION_WARNINGS')

# Monitor cluster installation
- name: Wait for up to 90 minutes for the cluster to report as installed
  uri:
    url: "{{ URL_ASSISTED_INSTALLER_CLUSTER }}"
    method: GET
    status_code: [200, 201]
    return_content: True
  register: cluster_output
  until: cluster_output.json.status in ['installed', 'error', 'cancelled']
  retries: 90
  delay: 60
  delegate_to: bastion

- name: "Fail installation because of cluster error (ERROR)"
  fail:
    msg: "Cluster installation failed - Reset the installation process to return to the configuration and try again"
  when: cluster_output.json.status == 'error'
  delegate_to: bastion

- name: "Fail installation because user cancelled (CANCELLED)"
  fail:
    msg: "Installation was canceled by user - Reset the installation process to return to the configuration and try again"
  when: cluster_output.json.status == 'cancelled'
  delegate_to: bastion
