---
- name: "Get list of images"
  ansible.builtin.set_fact:
    mor_images: "{{ mor_images | default([]) }}"

- name: "Add images for selected install types"
  ansible.builtin.set_fact:
    mor_images: "{{ mor_images + lookup('vars', 'mor_' + item) }}"
  loop: "{{ mor_list_install_type }}"
  when: >
    (mor_install_type is string and mor_install_type == item) or
    (mor_install_type is sequence and item in mor_install_type)

- name: "Cleanup images list"
  ansible.builtin.set_fact:
    mor_images: "{{ mor_images | unique | select | list }}"

- name: "Images to be mirrored"
  ansible.builtin.debug:
    msg: "{{ mor_images }}"
...
