---
- name: "Get list of images"
  ansible.builtin.set_fact:
    mor_images: "{{ mor_images | default([]) }}"

- name: "Add images for IPI installer"
  ansible.builtin.set_fact:
    mor_images: "{{ mor_images + mor_ipi }}"
  when:
    - mor_install_type == 'ipi'

- name: "Add images for vsphere installer"
  ansible.builtin.set_fact:
    mor_images: "{{ mor_images + mor_vsphere }}"
  when:
    - mor_install_type == 'vsphere'

- name: "Add images for ACM installation"
  ansible.builtin.set_fact:
    mor_images: "{{ mor_images + mor_acm }}"
  when:
    - mor_install_type == 'acm'

- name: "Add images for SNO installation"
  ansible.builtin.set_fact:
    mor_images: "{{ mor_images + mor_sno }}"
  when:
    - mor_install_type == 'sno'

- name: "Add images for Assisted installer"
  ansible.builtin.set_fact:
    mor_images: "{{ mor_images + mor_assisted_installer }}"
  when:
    - mor_install_type == 'assisted'

- name: "Add images for ABI"
  ansible.builtin.set_fact:
    mor_images: "{{ mor_images + mor_abi }}"
  when:
    - mor_install_type == 'abi'

- name: "Cleanup images list"
  ansible.builtin.set_fact:
    mor_images: "{{ mor_images | unique | select | list }}"

- name: "Images to be mirrored"
  ansible.builtin.debug:
    msg: "{{ mor_images }}"
...
