---
- name: "Check if OpenShift client tools have been unpacked"
  ansible.builtin.stat:
    path: "{{ mor_cache_dir }}/{{ mor_version }}/oc"
    get_checksum: false
  register: unpacked
  when:
    - not mor_force  # we don't care to stat files if we're forcing

- name: "Unarchive client tarball"
  vars:
    _mor_client_suffix: >-
      {{ mor_version is ansible.builtin.version('4.16', '>=') |
      ternary('-amd64-rhel' + ansible_distribution_major_version, '') }}
  ansible.builtin.unarchive:
    src: "{{ mor_cache_dir }}/{{ mor_version }}/openshift-client-linux{{ _mor_client_suffix }}-{{ mor_version }}.tar.gz"
    dest: "{{ mor_cache_dir }}/{{ mor_version }}"
    owner: "{{ mor_owner }}"
    group: "{{ mor_group }}"
    mode: "0755"
    remote_src: true
    exclude:
      - README.md
  register: _mor_client_downloaded
  until: _mor_client_downloaded is succeeded
  retries: 3
  delay: 60
  when:
    - mor_force or not unpacked.stat.exists

...
