---
- name: Validate_ that a storageclass is provided
  ansible.builtin.assert:
    that:
      - sm_storage_class is defined
    fail_msg: "A storage classname is required"

- name: Create Minio deployment
  ansible.builtin.include_tasks: install.yml
  when:
    - sm_action == 'install'

- name: Create Minio deployment
  ansible.builtin.include_tasks: cleanup.yml
  when:
    - sm_action == 'cleanup'
...
