---
- name: Read OAuth cluster
  community.kubernetes.k8s_info:
    api_version: config.openshift.io/v1
    kind: OAuth
    name: cluster
  register: _oau_oauth
  no_log: "{{ oau_secure_log | bool }}"

- name: Set Secret name
  ansible.builtin.set_fact:
    oau_secret_name: "{{ _oau_oauth.resources[0].spec.identityProviders[0].htpasswd.fileData.name | default('htpass-secret') }}"
  when:
    - _oau_oauth.resources | length

- name: Read Secret htpasswd
  community.kubernetes.k8s_info:
    api_version: v1
    kind: Secret
    name: "{{ _oau_oauth.resources[0].spec.identityProviders[0].htpasswd.fileData.name }}"
    namespace: openshift-config
  register: _oau_secret
  when:
    - _oau_oauth.resources | length
    - _oau_oauth.resources[0].spec.identityProviders | default([]) | json_query('[?type==`HTPasswd`]') | length
  no_log: "{{ oau_secure_log | bool }}"
