---
- name: "Create config dir"
  ansible.builtin.file:
    path: "{{ dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  tags: extract

- name: "Check if commands were extracted"
  ansible.builtin.stat:
    path: "{{ si_cache_dir }}/{{ version }}/openshift-install"
    get_checksum: false
  register: extracted_cmd
  delegate_to: "{{ si_cache_server }}" # This fact was defined in 10_get_oc.yml
  tags: extract

- name: "Unarchive installer tarball"
  ansible.builtin.unarchive:
    src: "{{ si_cache_dir }}/{{ version }}/openshift-install-linux-{{ version }}.tar.gz"
    dest: "{{ si_cache_dir }}/{{ version }}"
    owner: "{{ si_cache_server_user_id }}"
    group: "{{ si_cache_server_user_gid }}"
    mode: "0755"
    remote_src: true
    exclude:
      - README.md
  delegate_to: "{{ si_cache_server }}"
  when:
    - not extracted_cmd.stat.exists
  tags:
    - extract

# If the provisioner host got the installer, lets just copy it to /usr/local/bin
- name: "Copy openshift-install binary to binary path"
  ansible.builtin.copy:
    src: "{{ si_cache_dir }}/{{ version }}/openshift-install"
    dest: "{{ ocp_binary_path }}/openshift-install"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: '0755'
    remote_src: true
  become: true
  when:
    - si_cache_server == groups['provisioner'][0]
  tags:
    - extract

# If the registry host got the installer, lets just copy it to the prov host
- name: "Copy PullSecret and extract/copy openshit installer in disconnected mode"
  when:
    - si_cache_server != groups['provisioner'][0]
  tags:
    - extract
  block:
    - name: "Get the openshift install from registry host into temp file on control machine"
      ansible.builtin.fetch:
        dest: "{{ _si_tmp_dir.path }}/"
        flat: true
        src: "{{ si_cache_dir }}/{{ version }}/openshift-install"
      delegate_to: "{{ si_cache_server }}"

    - name: "Copy the openshift installer from control machine to the provisioner host"
      ansible.builtin.copy:
        src: "{{ _si_tmp_dir.path }}/openshift-install"
        dest: "{{ dir }}/openshift-install"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_gid }}"
        mode: "0755"
      become: true

    - name: "Copy openshift installer binary to binary path on provisioner"
      ansible.builtin.copy:
        src: "{{ dir }}/openshift-install"
        dest: "{{ ocp_binary_path }}/openshift-install"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_gid }}"
        mode: "0755"
        remote_src: true
      become: true
...
