---
argument_specs:
  get-credentials:
    short_description: Get credentials for the Spoke/Managed Cluster
    description: >
      Obtain the kubeconfig and kubeadmin credentials for the Spoke/Managed Cluster
    options:
      utils_cluster_name:
        type: str
        required: true
        description: The name of the Spoke/Managed Cluster
      utils_cluster_namespace:
        type: str
        required: true
        description: The namespace of the Spoke/Managed Cluster
  monitor-install:
    short_description: Monitor the installation of the Spoke Cluster
    description: >
      Monitor the installation of the Spoke Cluster tracking the progress in the AgentClusterInstall CR
    options:
      utils_cluster_name:
        type: str
        required: true
        description: The name of the Spoke Cluster
      utils_cluster_namespace:
        type: str
        required: true
        description: The namespace of the Spoke Cluster
      utils_monitor_timeout:
        type: int
        required: false
        default: 90
        description: >
          Timeout in minutes for the installation process. Default is 90 minutes.
      utils_monitor_wait_time:
        type: int
        required: false
        default: 3
        description: >
          Wait time in minutes between each progress check. Default is 3 minutes.
  image-sources:
    short_description: Convert IDMS or ICSP to registries.conf format for ACM spokes
    description: >
      Convert the ImageDigestMirrorSet (IDMS) or ImageContentSourcePolicies (ICSP) to the registries.conf format.
      Required by the spoke clusters in disconnected mode.
    options:
      utils_registry:
        type: str
        required: true
        description: >
          The custom/local registry to use for the spoke cluster. This is the registry where the images are stored.
          For example: `registry.example.com:5000`
      utils_hub_mirrors:
        type: list
        required: true
        elements: dict
        description: |
          List of mirrors and sources in the hub cluster. The format is:
          - mirrors:
              - mirror1
            source: source
      utils_imagesource_file:
        type: str
        required: true
        description: >
          A file with either IDMS or ICSP to transform into the registries.conf format.
          Additionally, it injects a mirror for the multicluster-engine image to the custom registry.
      utils_unqualified_search_registries:
        type: list
        required: false
        default: ['registry.redhat.io', 'docker.io']
        elements: str
        description: >
          List of unqualified search registries. Default is ['registry.redhat.io', 'docker.io']
  disconnect-agent:
    short_description: Config Assisted Service Agent for disconnected mode
    description: >
      Configure the Assisted Service Agent for disconnected mode. This includes creating a ConfigMap with the
      registries.conf and ca-bundle.crt files, and patching the AgentServiceConfig with the config map.
    options:
      utils_registries:
        type: str
        required: true
        description: >
          The registries.conf format to use by the Assisted Images service to connect to the custom registry.
          This is generated by the `image-sources` module.
      utils_ca_bundle:
        type: str
        required: true
        description: >
          The CA bundle to use by the Assisted Images service to connect to the custom registry.
      utils_cm_name:
        type: str
        required: false
        default: mirror-registry
        description: >
          The name of the ConfigMap to create. Default is `mirror-registry`.
      utils_ocp_version:
        type: str
        required: true
        description: >
          The OpenShift version to use for the spoke cluster. This is used to determine the image versions.
      utils_iso_url:
        type: str
        required: true
        description: >
          The URL of the ISO image to use for the spoke cluster. This is used to determine the image versions.
      utils_root_fs_url:
        type: str
        required: true
        description: >
          The URL of the root filesystem image to use for the spoke cluster. This is used to determine the image versions.
