---
- name: Deploy hypershift cluster
  ansible.builtin.shell:
    cmd: >
      set -e;
      {{ ah_hcp_cli_path }} create cluster {{ ah_cluster_type }}
      --name={{ ah_cluster_generated_name }}
      {%- if ah_base_domain is defined %} --base_domain={{ ah_base_domain }}{%- endif %}
      --pull-secret={{ ah_pullsecret_file }}
      --namespace={{ ah_clusters_ns }}
      --cluster-cidr={{ ah_cluster_network_cidr }}
      --memory="{{ ah_node_memory }}"
      --node-pool-replicas={{ ah_node_pool_replicas }}
      --release-image={{ ah_release_image }}
      {%- if ah_ics is defined %} --image-content-sources "{{ ah_ics }}"{%- endif %}
      {%- if ah_ca_bundle_file is defined %} --additional-trust-bundle "{{ ah_ca_bundle_file }}"{%- endif %}
      {%- if ah_hc_annotations | length >0 %} --annotations {{ ah_hc_annotations }}{%- endif %}
      {%- if ah_ssh_key | length >0 %} --ssh-key {{ ah_ssh_key }}{%- endif %}
      {% if ah_control_plane_availability_policy is defined %}
      --control-plane-availability-policy="{{ ah_control_plane_availability_policy }}"
      {% endif %}
  changed_when: false

- name: Remove working directory
  ansible.builtin.file:
    path: "{{ hs_tmp_dir.path }}"
    state: absent
  when: hs_tmp_dir is defined

- name: Wait for Hosted Cluster initialization
  ansible.builtin.pause:
    seconds: 10

- name: Monitor Hosted Cluster Control-Plane availability
  kubernetes.core.k8s_info:
    api_version: hypershift.openshift.io/v1beta1
    kind: HostedCluster
    namespace: "{{ ah_clusters_ns }}"
    name: "{{ ah_cluster_generated_name }}"
  register: ah_hc_info
  until:
    - ah_hc_info.resources is defined
    - ah_hc_info.resources | length
    - ah_hc_info | json_query('resources[0].status.conditions[? type==`Available`]') | length
    - ah_hc_info | json_query('resources[0].status.conditions[? type==`Available`].status') | first | bool
  retries: 90
  delay: 10
  no_log: true

- name: Monitor Hosted Cluster Nodes availability
  kubernetes.core.k8s_info:
    api_version: hypershift.openshift.io/v1beta1
    kind: HostedCluster
    namespace: "{{ ah_clusters_ns }}"
    name: "{{ ah_cluster_generated_name }}"
  register: ah_hc_info
  until:
    - ah_hc_info.resources is defined
    - ah_hc_info.resources | length
    - ah_hc_info | json_query('resources[0].status.conditions[? type==`Available`]') | length
    - ah_hc_info | json_query('resources[0].status.conditions[? type==`Available`].status') | first | bool
    - ah_hc_info | json_query('resources[0].status.version.history') | length
    - ah_hc_info | json_query('resources[0].status.version.history[0].state') == "Completed"
  retries: 30
  delay: 60
  no_log: true

- name: Get hosted cluster credentials
  ansible.builtin.include_role:
    name: redhatci.ocp.acm.utils
    tasks_from: get-credentials
  vars:
    utils_cluster_name: "{{ ah_cluster_generated_name }}"
    utils_cluster_namespace: "{{ ah_clusters_ns }}"

...
