---
- name: Get Hosted Cluster info
  kubernetes.core.k8s_info:
    api_version: hypershift.openshift.io/v1beta1
    kind: HostedCluster
    namespace: "{{ ah_clusters_ns }}"
    name: "{{ ah_cluster_generated_name }}"
  register: hosted_cluster

- name: Delete cluster
  ansible.builtin.shell:
    cmd: >
      set -e;
      {{ ah_hcp_cli_path }} destroy cluster {{ ah_cluster_type }}
      --name={{ ah_cluster_generated_name }}
      --namespace={{ ah_clusters_ns }}
      --infra-id={{ ah_cluster_generated_name }}
  changed_when: false
  when:
    - hosted_cluster.resources | default([]) | length == 1

- name: Confirm that HCP is deleted
  kubernetes.core.k8s_info:
    api_version: hypershift.openshift.io/v1beta1
    kind: HostedCluster
    namespace: "{{ ah_clusters_ns }}"
    name: "{{ ah_cluster_generated_name }}"
  retries: 10
  delay: 6
  register: _ah_hosted_cluster
  until:
    - _ah_hosted_cluster is defined
    - _ah_hosted_cluster.resources is defined
    - _ah_hosted_cluster.resources | length == 0
  when:
    - hosted_cluster.resources | default([]) | length == 1
...
