---
- name: Install the NetObservability stack
  when:
    - setup_netobserv_stack_action == "install"
  block:
    - name: Pre-run validations
      ansible.builtin.include_tasks: validation.yml

    - name: Set up the NetObservability stack
      ansible.builtin.include_tasks: setup.yml

    - name: Validate_ the NetObservability resources
      ansible.builtin.include_tasks: verify.yml

- name: Cleanup NetObservability stack resources
  when:
    - setup_netobserv_stack_action == "cleanup"
  block:
    - name: Cleanup Logging stack resources
      ansible.builtin.include_tasks: cleanup.yml
...
