---
- name: Set test file contents
  set_fact:
    contents: "{{ lookup('template', 'test_file.j2') }}"

- name: Copy file to http_store
  copy:
    content: "{{ contents }}"
    dest: "{{ http_store_dir }}/{{ test_file_name }}"
    mode: 0644
    setype: httpd_sys_content_t
  become: true
  delegate_to: http_store

- name: Retrieve file from http_store
  uri:
    url: "{{ http_host }}/{{ test_file_name }}"
    return_content: true
  register: _vhs_response
  delegate_to: bastion
  retries: 12
  delay: 5
  until: _vhs_response.status == 200

- name: Check content matches
  assert:
    that:
      _vhs_response.content == contents
    quiet: true

- name: Remove file on http_store
  file:
    path: "{{ http_store_dir }}/{{ test_file_name }}"
    state: absent
  become: true
  delegate_to: http_store
