---
- name: "Install the cluster Logging stack"
  when:
    - ol_action == 'install'
  block:
    - name: "Pre-run validations"
      ansible.builtin.include_tasks: pre-run.yml

    - name: "Set up the cluster logging subsystem"
      ansible.builtin.include_tasks: setup-logging.yml

    - name: "Validate_ cluster logging subsystem"
      ansible.builtin.include_tasks: validate-stack.yml

- name: "Cleanup Logging stack resources"
  when:
    - ol_action == 'cleanup'
  block:
    - name: "Cleanup Logging stack resources"
      ansible.builtin.include_tasks: clean-resources.yml
...
